name: tests
on:
  pull_request_target:
    branches: 
      - master
      - dev
    types: [assigned, opened, synchronize, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install meson
        run: apt update && apt install meson -y

      - name: setup
        run: make setup

      - name: compile
        run: make compile

      - name: run tests
        run: make runtest
